### ISSUE TITLE
Issue with custom registry

### ISSUE THREAD

**Issue by crstnbr** [JuliaRegistries/TagBot#33] opened 2019-11-10 11:26 UTC
I have a custom registry ([TrebstRegistry](https://github.com/crstnbr/TrebstRegistry)) and am trying to enable TagBot for a package registered therein ([TestPackage2.jl](https://github.com/crstnbr/TestPackage2.jl)).

My [TagBot.yml workflow](https://github.com/crstnbr/TestPackage2.jl/blob/master/.github/workflows/TagBot.yml) looks like this:

```yml
name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://github.com/crstnbr/TrebstRegistry
```
Note the extra `registry` entry which I added as explained in the TagBot readme.

However, when this workflow runs, I get an error:
> fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

Check yourself here: https://github.com/crstnbr/TestPackage2.jl/commit/c3a932d42f94c3a592ee2e9c1b0f7d7c15c4bb17/checks?check_suite_id=303890250

I don't know how to debug this. Is this a TagBot issue, one with my registry, or just me wrongly setting up things?

Any help is very much appreciated!
Carsten

**Comment by christopher-dG** [comment] 2019-11-10 11:45
Hi! Sorry for the inconvenience, the new Actions-based TagBot is not well-tested yet, so the problem is 100% mine.
 
I've just pushed a new version, which you will receive automatically. You will need to change the value for `registry` to just `crstnbr/TrebstRegistry`.

Once you've done that, things will hopefully work properly, but please report back with any more errors :slightly_smiling_face:. Sorry to make you my guinea pig haha.

**Comment by crstnbr** [comment] 2019-11-10 11:48
No worries :) Thank you for writing/maintaining this bot!

I've made the change and will report back!

**Comment by christopher-dG** [comment] 2019-11-10 12:10
I see another error, I'll figure it out :slightly_smiling_face:

**Comment by crstnbr** [comment] 2019-11-10 14:26
Great. Let me know if there is something I can do on my side.

**Comment by crstnbr** [comment] 2019-11-10 15:27
Seems to be working. Thanks for fixing it!

I'll play around a bit more, but let's close this for now. Thanks again!

**Comment by christopher-dG** [comment] 2019-11-10 15:30
Yeah I'm almost there, I'm manually pushing Docker tags to avoid making 5000 GitHub releases haha. You won't have to change anything :smile:

**Comment by crstnbr** [comment] 2019-11-10 16:47
Unfortunately, it didn't quite work. For another package ([TestPackage.jl](http://github.com/crstnbr/TestPackage.jl)) it tagged a release for the first version in the registry but failed to add more releases afterwards.

See https://github.com/crstnbr/TestPackage.jl/commit/87fddf746c442412969583211638ac0cd3625499/checks?check_suite_id=304057901

**Comment by crstnbr** [comment] 2019-11-10 17:45
PS: The bot is now tagging all versions step by step, failing after tagging one in each run.

**Comment by christopher-dG** [comment] 2019-11-10 23:21
Should be fixed now.

**Closed** 2019-11-13 05:25 UTC
