### ISSUE TITLE
Issues with TagBot

### ISSUE THREAD

**Issue by tknopp** [JuliaRegistries/TagBot#191] opened 2021-03-23 21:09 UTC
Hi, 

I have a package where tagbot seems to have issues and does not make a tag: see https://github.com/tknopp/RedPitayaDAQServer/issues/25#issuecomment-805201616

One issue might be that my package has the Julia code in a subdir "src/client/julia". Do I need to change something to account for this?

Thank you!

Tobi

**Comment by DilumAluthge** [comment] 2021-03-23 21:12
@christopher-dG Any idea what's going on here?

I'll also ping @GunnarFarneback who is very knowledgeable about the subdirectory stuff.

**Comment by DilumAluthge** [comment] 2021-03-23 21:28
From the TagBot log, it thinks that the package is not registered: https://github.com/tknopp/RedPitayaDAQServer/runs/2178712647?check_suite_focus=true

But of course the package is registered: https://github.com/JuliaRegistries/General/pull/32648

**Comment by christopher-dG** [comment] 2021-03-23 21:39
TagBot doesn't support subdir packages. #157

**Comment by DilumAluthge** [comment] 2021-03-23 21:44
Duplicate of #157

**Closed by DilumAluthge** 2021-03-23 21:44 UTC
Labels: bug

**Comment by tknopp** [comment] 2021-03-23 21:45
thanks! Will be patient then.
