### ISSUE TITLE
Could not find registry PR

### ISSUE THREAD

**Issue by cadojo** [JuliaRegistries/TagBot#262] opened 2023-05-01 05:43 UTC
I'm seeing warnings in my TagBot CI job logs. A release and tag are created successfully, but no documentation build is triggered. Are these two issues potentially related?

https://github.com/cadojo/HorizonsAPI.jl/actions/runs/4848205877/jobs/8639117151#step:3:40

**Comment by ChrisRackauckas** [comment] 2023-05-03 10:09
https://github.com/SciML/SciMLSensitivity.jl/actions/runs/4870575841/jobs/8686495391#step:3:44 same here.

**Comment by ChrisRackauckas** [comment] 2023-05-03 10:09
Looks like a duplicate of https://github.com/JuliaRegistries/TagBot/issues/258

**Closed** 2023-08-25 12:38 UTC
